CREATE TABLE IF NOT EXISTS topo_nodes (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	type VARCHAR(32) NOT NULL,
	host_ref BIGINT UNSIGNED NULL,
	attrs JSON NOT NULL,
	created_at INT UNSIGNED NOT NULL DEFAULT 0,
	updated_at INT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (id),
	KEY topo_nodes_1 (type),
	KEY topo_nodes_2 (host_ref),
	CONSTRAINT topo_nodes_1 FOREIGN KEY (host_ref) REFERENCES hosts (hostid) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS topo_edges (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	type VARCHAR(32) NOT NULL,
	src_id BIGINT UNSIGNED NOT NULL,
	dst_id BIGINT UNSIGNED NOT NULL,
	attrs JSON NOT NULL,
	created_at INT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (id),
	KEY topo_edges_1 (src_id, type),
	KEY topo_edges_2 (dst_id, type),
	CONSTRAINT topo_edges_1 FOREIGN KEY (src_id) REFERENCES topo_nodes (id) ON DELETE CASCADE,
	CONSTRAINT topo_edges_2 FOREIGN KEY (dst_id) REFERENCES topo_nodes (id) ON DELETE CASCADE
) ENGINE=InnoDB;